### ISSUE TITLE
Programmer Competency Matrix

### ISSUE THREAD

**Issue by WilSil11** [nhivp/Awesome-Embedded#21]
Clicking on the link for Programmer Competency Matrix leads to the server not found or not connecting:
![image](https://github.com/nhivp/Awesome-Embedded/assets/11875564/338d922a-9298-4e5c-a1e0-f8efbea2b69c)

I recommend updating this link to: https://www.sijinjoseph.com/programmer-competency-matrix/

**Comment by hk77cn** [comment]
这是来自QQ邮箱的自动回复邮件。

您好，您所收到的回复并不代表我已经看过您的邮件，我将在看过您的邮件后，亲自回复您的邮件。谢谢！

**Comment by nhivp** [comment]
Nice, could you please help write a patch for the update?
