### ISSUE TITLE
Add estdlib

### ISSUE THREAD

**Issue by malachib** [nhivp/Awesome-Embedded#28]
Hi, could we add a link to https://github.com/malachi-iot/estdlib ?  It's like a spiritual cousin of recently-added ETL lib.

Full disclosure: I'm the author :)

**Comment by hk77cn** [comment]
这是来自QQ邮箱的自动回复邮件。

您好，您所收到的回复并不代表我已经看过您的邮件，我将在看过您的邮件后，亲自回复您的邮件。谢谢！

**Comment by nhivp** [comment]
Thank you, @malachib, for the suggestion. It looks great. Could you create a pull request for it?

**Comment by hk77cn** [comment]
这是来自QQ邮箱的自动回复邮件。

您好，您所收到的回复并不代表我已经看过您的邮件，我将在看过您的邮件后，亲自回复您的邮件。谢谢！

**Comment by malachib** [comment]
Done! https://github.com/nhivp/Awesome-Embedded/pull/29

**Comment by nhivp** [comment]
Thanks!
