### ISSUE TITLE
Coding-interview-university link

### ISSUE THREAD

**Issue by jpatrick5402** [nhivp/Awesome-Embedded#30]
For the code-interview-university link in the interview section, it should link to https://github.com/jwasham/coding-interview-university
since the fork that it currently links to is over 1000 commits behind.

**Comment by hk77cn** [comment]
这是来自QQ邮箱的自动回复邮件。

您好，您所收到的回复并不代表我已经看过您的邮件，我将在看过您的邮件后，亲自回复您的邮件。谢谢！

**Comment by nhivp** [comment]
Fixed, thanks @jpatrick5402 for catching that.
